package httpapi

import "net/http"

func (a *Server) routes() http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /api/health", a.handleHealth)
	mux.HandleFunc("GET /api/auth/status", a.handleAuthStatus)
	mux.HandleFunc("POST /api/auth/login", a.handleAuthLogin)
	mux.HandleFunc("GET /api/setup/status", a.handleSetupStatus)
	mux.HandleFunc("POST /api/setup/init", a.handleSetupInit)
	mux.HandleFunc("GET /api/model-providers", a.handleListModelProviders)
	mux.HandleFunc("POST /api/model-providers", a.handleCreateModelProvider)
	mux.HandleFunc("POST /api/model-providers/test", a.handleTestModelProvider)
	mux.HandleFunc("POST /api/model-providers/models", a.handleListProviderModels)
	mux.HandleFunc("PUT /api/model-providers/{id}", a.handleUpdateModelProvider)
	mux.HandleFunc("DELETE /api/model-providers/{id}", a.handleDeleteModelProvider)
	mux.HandleFunc("GET /api/projects", a.handleListProjects)
	mux.HandleFunc("POST /api/projects", a.handleCreateProject)
	mux.HandleFunc("PUT /api/projects/{id}", a.handleUpdateProject)
	mux.HandleFunc("POST /api/projects/{id}/pin", a.handlePinProject)
	mux.HandleFunc("DELETE /api/projects/{id}", a.handleDeleteProject)
	mux.HandleFunc("GET /api/projects/{id}/prompt-preview", a.handleProjectPromptPreview)
	mux.HandleFunc("GET /api/data/status", a.handleDataStatus)
	mux.HandleFunc("GET /api/system/status", a.handleSystemStatus)
	mux.HandleFunc("GET /api/config", a.handleGetConfig)
	mux.HandleFunc("POST /api/config", a.handleSaveConfig)
	mux.HandleFunc("GET /api/mcp-config", a.handleGetMCPConfig)
	mux.HandleFunc("POST /api/mcp-config", a.handleSaveMCPConfig)
	mux.HandleFunc("GET /api/mcp/tools", a.handleListMCPTools)
	mux.HandleFunc("GET /api/mcp/status", a.handleMCPStatus)
	mux.HandleFunc("GET /api/mcp/test", a.handleTestMCPServer)
	mux.HandleFunc("GET /api/agent-tasks", a.handleListAgentTasks)
	mux.HandleFunc("GET /api/agent-tasks/{id}", a.handleGetAgentTask)
	mux.HandleFunc("DELETE /api/agent-tasks/{id}", a.handleDeleteAgentTask)
	mux.HandleFunc("GET /api/sessions/{id}/agent-task", a.handleGetSessionAgentTask)
	mux.HandleFunc("GET /api/mcp/confirmations", a.handleListMCPConfirmations)
	mux.HandleFunc("POST /api/mcp/confirmations/{id}/resolve", a.handleResolveMCPConfirmation)
	mux.HandleFunc("POST /api/mcp/call", a.handleCallMCPTool)
	mux.HandleFunc("GET /api/scheduled-tasks", a.handleListScheduledTasks)
	mux.HandleFunc("POST /api/scheduled-tasks", a.handleCreateScheduledTask)
	mux.HandleFunc("PUT /api/scheduled-tasks/{id}", a.handleUpdateScheduledTask)
	mux.HandleFunc("POST /api/scheduled-tasks/{id}/pin", a.handlePinScheduledTask)
	mux.HandleFunc("DELETE /api/scheduled-tasks/{id}", a.handleDeleteScheduledTask)
	mux.HandleFunc("POST /api/scheduled-tasks/{id}/run", a.handleRunScheduledTask)
	mux.HandleFunc("GET /api/scheduled-tasks/{id}/runs", a.handleListScheduledTaskRuns)
	mux.HandleFunc("GET /api/sessions", a.handleListSessions)
	mux.HandleFunc("GET /api/sessions/search", a.handleSearchSessions)
	mux.HandleFunc("POST /api/sessions", a.handleCreateSession)
	mux.HandleFunc("GET /api/sessions/{id}", a.handleGetSession)
	mux.HandleFunc("DELETE /api/sessions/{id}", a.handleDeleteSession)
	mux.HandleFunc("POST /api/sessions/{id}/rename", a.handleRenameSession)
	mux.HandleFunc("POST /api/sessions/{id}/pin", a.handlePinSession)
	mux.HandleFunc("POST /api/sessions/{id}/model", a.handleUpdateSessionModel)
	mux.HandleFunc("POST /api/sessions/{id}/clone", a.handleCloneSession)
	mux.HandleFunc("POST /api/sessions/{id}/branch", a.handleBranchSession)
	mux.HandleFunc("POST /api/sessions/{id}/messages", a.handleEditMessage)
	mux.HandleFunc("GET /api/sessions/{id}/export", a.handleExportSession)
	mux.HandleFunc("GET /api/sessions/{id}/tool-event", a.handleGetSessionToolEvent)
	mux.HandleFunc("GET /api/sessions/{id}/tool-events/{event_id}", a.handleGetSessionToolEventByID)
	mux.HandleFunc("GET /api/sessions/{id}/context-preview", a.handleContextPreview)
	mux.HandleFunc("GET /api/sessions/{id}/system-prompt", a.handleSessionSystemPrompt)
	mux.HandleFunc("POST /api/files", a.handleUploadFile)
	mux.HandleFunc("GET /api/files/{id}", a.handleDownloadFile)
	mux.HandleFunc("GET /api/model-images/{id}/{name}", a.handleModelImageFile)
	mux.HandleFunc("GET /api/model-images/{id}", a.handleModelImageFile)
	mux.HandleFunc("POST /api/chat", a.handleChat)
	mux.HandleFunc("POST /api/chat/stream", a.handleChatStream)
	mux.HandleFunc("GET /api/chat/jobs", a.handleListChatJobs)
	mux.HandleFunc("POST /api/chat/jobs", a.handleCreateChatJob)
	mux.HandleFunc("GET /api/chat/jobs/{id}/events", a.handleChatJobEvents)
	mux.HandleFunc("POST /api/chat/jobs/{id}/cancel", a.handleCancelChatJob)
	mux.HandleFunc("POST /api/chat/jobs/{id}/guide", a.handleGuideChatJob)

	mux.Handle("/", a.webHandler())

	return logRequest(securityHeaders(gzipMiddleware(a.authMiddleware(mux))))
}
