package chatdock

import "net/http"

func (a *App) routes() http.Handler {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /api/health", a.handleHealth)
	mux.HandleFunc("GET /api/auth/status", a.handleAuthStatus)
	mux.HandleFunc("POST /api/auth/login", a.handleAuthLogin)
	mux.HandleFunc("GET /api/setup/status", a.handleSetupStatus)
	mux.HandleFunc("POST /api/setup/init", a.handleSetupInit)
	mux.HandleFunc("GET /api/model-providers", a.handleListModelProviders)
	mux.HandleFunc("POST /api/model-providers", a.handleCreateModelProvider)
	mux.HandleFunc("POST /api/model-providers/test", a.handleTestModelProvider)
	mux.HandleFunc("POST /api/model-providers/models", a.handleListProviderModels)
	mux.HandleFunc("/api/model-providers/", a.handleModelProviderRoute)
	mux.HandleFunc("GET /api/workspaces", a.handleListWorkspaces)
	mux.HandleFunc("POST /api/workspaces", a.handleCreateWorkspace)
	mux.HandleFunc("/api/workspaces/", a.handleWorkspaceRoute)
	mux.HandleFunc("GET /api/data/status", a.handleDataStatus)
	mux.HandleFunc("GET /api/system/status", a.handleSystemStatus)
	mux.HandleFunc("GET /api/config", a.handleGetConfig)
	mux.HandleFunc("POST /api/config", a.handleSaveConfig)
	mux.HandleFunc("GET /api/prompts", a.handleListPrompts)
	mux.HandleFunc("POST /api/prompts", a.handleCreatePrompt)
	mux.HandleFunc("POST /api/prompts/select", a.handleSelectPrompt)
	mux.HandleFunc("GET /api/mcp-config", a.handleGetMCPConfig)
	mux.HandleFunc("POST /api/mcp-config", a.handleSaveMCPConfig)
	mux.HandleFunc("GET /api/mcp/tools", a.handleListMCPTools)
	mux.HandleFunc("GET /api/mcp/status", a.handleMCPStatus)
	mux.HandleFunc("GET /api/mcp/test", a.handleTestMCPServer)
	mux.HandleFunc("GET /api/mcp/confirmations", a.handleListMCPConfirmations)
	mux.HandleFunc("/api/mcp/confirmations/", a.handleMCPConfirmationRoute)
	mux.HandleFunc("POST /api/mcp/call", a.handleCallMCPTool)
	mux.HandleFunc("GET /api/scheduled-tasks", a.handleListScheduledTasks)
	mux.HandleFunc("POST /api/scheduled-tasks", a.handleCreateScheduledTask)
	mux.HandleFunc("PUT /api/scheduled-tasks/{id}", a.handleUpdateScheduledTask)
	mux.HandleFunc("DELETE /api/scheduled-tasks/{id}", a.handleDeleteScheduledTask)
	mux.HandleFunc("POST /api/scheduled-tasks/{id}/run", a.handleRunScheduledTask)
	mux.HandleFunc("GET /api/scheduled-tasks/{id}/runs", a.handleListScheduledTaskRuns)
	mux.HandleFunc("GET /api/sessions", a.handleListSessions)
	mux.HandleFunc("GET /api/sessions/search", a.handleSearchSessions)
	mux.HandleFunc("POST /api/sessions", a.handleCreateSession)
	mux.HandleFunc("/api/sessions/", a.handleSessionRoute)
	mux.HandleFunc("POST /api/files", a.handleUploadFile)
	mux.HandleFunc("GET /api/files/{id}", a.handleDownloadFile)
	mux.HandleFunc("GET /api/model-images/{id}/{name}", a.handleModelImageFile)
	mux.HandleFunc("GET /api/model-images/{id}", a.handleModelImageFile)
	mux.HandleFunc("POST /api/chat", a.handleChat)
	mux.HandleFunc("POST /api/chat/stream", a.handleChatStream)
	mux.HandleFunc("GET /api/chat/jobs", a.handleListChatJobs)
	mux.HandleFunc("POST /api/chat/jobs", a.handleCreateChatJob)
	mux.HandleFunc("GET /api/chat/jobs/{id}/events", a.handleChatJobEvents)
	mux.HandleFunc("POST /api/chat/jobs/{id}/cancel", a.handleCancelChatJob)
	mux.HandleFunc("POST /api/chat/jobs/{id}/guide", a.handleGuideChatJob)

	mux.Handle("/", a.webHandler())

	return logRequest(gzipMiddleware(a.authMiddleware(mux)))
}
